# Generated by Django 5.1.5 on 2025-06-10 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_text', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('offer_type', models.CharField(choices=[('sale', 'Sale'), ('lease', 'Lease')], max_length=10)),
                ('industrial_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mezzanine_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('office_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('industrial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mezzanine_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('office_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Premise',
                'verbose_name_plural': 'Premises',
            },
        ),
    ]
