# Generated by Django 5.1.5 on 2025-06-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='offer_type',
            field=models.CharField(choices=[('продажа', 'Продажа'), ('аренда', 'Аренда')], max_length=10),
        ),
    ]
