# Generated by Django 5.1.5 on 2025-06-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_alter_premise_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
