# Generated by Django 5.1.5 on 2025-06-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_alter_premise_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premise',
            name='location_text',
        ),
        migrations.AddField(
            model_name='premise',
            name='highway',
            field=models.CharField(choices=[('1', 'в черте МКАД'), ('2', 'Ленинградское шоссе'), ('3', 'Дмитровское шоссе'), ('4', 'Ярославское шоссе'), ('5', 'Щелковское шоссе'), ('6', 'Горьковское шоссе'), ('7', 'Новорязанское шоссе'), ('8', 'Каширское шоссе'), ('9', 'М-4'), ('10', 'Симферопольское шоссе'), ('11', 'Калужское шоссе'), ('12', 'Киевское шоссе'), ('13', 'Минское шоссе'), ('14', 'Новорижское шоссе'), ('15', 'Волоколамское шоссе'), ('16', 'Пятницкое шоссе'), ('17', 'М-11')], default=1, max_length=21),
            preserve_default=False,
        ),
    ]
